name: Autodeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy-web:
    runs-on: ["self-hosted", "web-chal"]
    steps:
      - uses: actions/checkout@v2
      - name: build images
        run: ctfdbot build web.chal.csaw.io .
      - name: update ctfd
        run: ctfdbot update web.chal.csaw.io .
      - name: deploy containers
        run: ctfdbot deploy web.chal.csaw.io
        
  deploy-pwn:
    runs-on: ["self-hosted", "pwn-chal"]
    steps:
      - uses: actions/checkout@v2
      - name: build images
        run: ctfdbot build pwn.chal.csaw.io .
      - name: update ctfd
        run: ctfdbot update pwn.chal.csaw.io .
      - name: deploy containers
        run: ctfdbot deploy pwn.chal.csaw.io
                
  deploy-rev:
    runs-on: ["self-hosted", "rev-chal"]
    steps:
      - uses: actions/checkout@v2
      - name: build images
        run: ctfdbot build rev.chal.csaw.io .
      - name: update ctfd
        run: ctfdbot update rev.chal.csaw.io .
      - name: deploy containers
        run: ctfdbot deploy rev.chal.csaw.io
                
  deploy-crypto:
    runs-on: ["self-hosted", "crypto-chal"]
    steps:
      - uses: actions/checkout@v2
      - name: build images
        run: ctfdbot build crypto.chal.csaw.io .
      - name: update ctfd
        run: ctfdbot update crypto.chal.csaw.io .
      - name: deploy containers
        run: ctfdbot deploy crypto.chal.csaw.io
        
